### ISSUE TITLE
Accidentally Uploaded Builds

### ISSUE THREAD

**Issue by dtip** [conda-forge/magics-feedstock#28]
There are a couple of magics builds which were accidentally uploaded to conda-forge and are causing issues. These are the culprits:
```
magics                         4.0.0      h5828bd8_0  conda-forge
magics                         4.0.0   h5828bd8_1016  conda-forge
```
Could someone please remove these builds? I'm not certain how to do it - fairly sure you need to be a conda-forge admin. @ocefpaf Any chance you could help with this?

**Comment by ocefpaf** [comment]
> Could someone please remove these builds? I'm not certain how to do it - fairly sure you need to be a conda-forge admin. @ocefpaf Any chance you could help with this?

Done. Can you please check if I got it correctly?

https://anaconda.org/conda-forge/magics/files?version=4.0.0

**Comment by dtip** [comment]
Thanks @ocefpaf . I'm afraid I've been too specific with the build numbers. Could you please also mark builds 0 and 1016 for v4.0.0 on Windows and MacOS as broken?

Also for future reference, is there any way I (or one of the other maintainers) can do this directly if it happens again?

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf . I'm afraid I've been too specific with the build numbers. Could you please also mark builds 0 and 1016 for v4.0.0 on Windows and MacOS as broken?

Done.

> Also for future reference, is there any way I (or one of the other maintainers) can do this directly if it happens again?

Sadly no. We don't have a way to give the right rights granularity for maintainers on the channel yet. For now you have to ask @conda-forge/core to do it.

**Comment by dtip** [comment]
Fair enough. Thanks for the help!
