### ISSUE TITLE
Wrong package version installed by default

### ISSUE THREAD

**Issue by dtip** [conda-forge/magics-feedstock#31]
Magics v3.4.0.10 build 1009 was the last build without Qt as a dep. Since adding Qt as a dep, running ```conda install -c conda-forge magics``` tries to install v3.4.0.10 1009 instead of the latest build, v4.0.0 1002.

We can get the correct version with ```conda install -c conda-forge magics=4.0.0``` or ```conda install -c conda-forge magics qt``` but really we want the default behaviour to be to install the latest package.

Even if we manually install v4.0.0, if we run ```conda install -c conda-forge magics``` again it tries to downgrade to v3.4.0.10 1009. That's not desirable behaviour.

The output of ```conda install -c conda-forge magics -v -v -v``` shows:
```
DEBUG conda.resolve:filter_group(400): magics: pruned from 12 -> 6
```
There are a couple of older conda issues on the web where people have seen the latest versions of their packages scored badly by conda if they include more deps - it seems like that's what's happening here.

@conda-forge/core could you please advise how we can make sure the latest v4.0.0 build is installed by default? Is there a way to do it other than removing the old v3 builds from conda-forge/magics/files?

**Comment by dtip** [comment]
@ocefpaf Any thoughts on the best way to fix this?

Could we simply delete all magics v2 and v3 files from the Anaconda cloud?

**Comment by ocefpaf** [comment]
> Could we simply delete all magics v2 and v3 files from the Anaconda cloud?

That is probably the best way to fix this. If v2 and v3 are needed I recommend rebuilding than later. BTW, we don't really remove, we just move than to a `broken` label and the package is still accessible to users who know that they are doing. Do you want me to apply that to https://anaconda.org/conda-forge/magics/files ?

**Comment by dtip** [comment]
Thanks for the info :)

@StephanSiemen Are you happy for us to go ahead with this? You know more about magics users' requirements than I do!

**Comment by ocefpaf** [comment]
> @StephanSiemen Are you happy for us to go ahead with this? You know more about magics users' requirements than I do!

I'm fine with that but I don't think I know more about the users than you :smile: 

It is a reversible solution in case that becomes a problem down the road but, like I mention above, users looking for reproducibility will still have access to the package via the broken label and the average user wants the latest thing that just works.

**Comment by ocefpaf** [comment]
Done! Only version 4 is available on the `main` label. Can you please check if I got it right?

https://anaconda.org/conda-forge/magics/files

**Comment by dtip** [comment]
Looks right to me! Thanks.

**Comment by dtip** [comment]
Sorry @ocefpaf , I spoke too soon.

`conda search -c conda-forge magics` still lists the v2 and v3 packages, and `conda install -c conda-forge magics` tries to install magics v3.4.0.10 instead of v4.

Any idea why?

**Comment by ocefpaf** [comment]
It may take ~20 minutes for the index to be updated. Can you wait a little but and try again? Also, cleaning your cache may help: `conda clean --all --yes`

**Comment by dtip** [comment]
Thanks :) I tried cleaning the cache already - it's probably the index delay. I'll wait.

**Comment by dtip** [comment]
All good
